blank_issues_enabled: false
contact_links:
  - name: ğŸ¤” I have a question
    url: https://github.com/dsmrreader/dsmr-reader/discussions/categories/q-a-ask-for-help
    about: You'd like to ask something generic. Please consider searching previous discussions in Q&A, or creating a new one. You can find many commonly asked questions in the Q&A of Discussions. Many were originally created as Issues but later relocated to here, inclusing any answers given.
  - name: âï¸ I have an issue specifically related to running DSMR-reader in Docker
    url: https://github.com/xirixiz/dsmr-reader-docker/issues
    about: Whenever you are 100% sure your issue is related to running in Docker (or the image used), check out Xirixiz's project as well!
